server:
  port: 9099
  servlet:
    context-path: /la

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://101.43.115.8:6033/hape_db?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: ppxwmz
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    timeout: 30000
    host: 101.43.115.8
    port: 9736
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.115.8:8488


#  mail:
#    host: smtp.163.com
#    password: UUPLZRHJKISZVKBL # 授权码
#    username: wuyidijun@163.com
#    properties:
#      mail:
#        smtl:
#          auth: true
#          starttls:
#            enable: true
#            required: true

mybatis-plus:
  mapper-locations: com.hape.dao.*.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.hape.dao.*.po

knife4j: # http://localhost:9099/la/doc.html
  enable: false
  openapi:
    title: languageApi
    description: "language's api description"
    email:
    contact: hape
    group: #用于定义API文档中的分组信息。
      apiPerson:
        group-name: front
        api-rule: package
        api-rule-resources:
          - com.ppx.controller.web
          - header:
              name: token
              description: Authorization
      apiBack:
        group-name: back
        api-rule: package
        api-rule-resources:
          - com.ppx.controller.back
  basic:
    username: admin
    password: admin